from __future__ import annotations

import re
import shlex
import sqlite3
import uuid
from datetime import UTC, datetime

from nexus.db import get_project, list_concepts
from nexus.models import Concept

# Only allow package names that look like real packages (alphanumeric, @scope, hyphens, dots).
_SAFE_PKG = re.compile(r"^@?[a-zA-Z0-9][\w./-]*$")


def _safe_pkg_name(raw: str) -> str | None:
    name = raw.strip()
    if not name or not _SAFE_PKG.match(name):
        return None
    return name


def generate_setup_script(
    conn: sqlite3.Connection, project_id: str,
    *, context_query: str | None = None,
) -> str:
    project = get_project(conn, project_id)
    if not project:
        return "# Error: project not found\n"

    concepts = _filter_concepts(conn, project_id, context_query)
    if not concepts:
        return f"# No installable concepts found for {shlex.quote(project.name)}\n"

    npm_deps: list[str] = []
    npm_dev: list[str] = []
    pip_deps: list[str] = []
    other_cmds: list[str] = []

    for c in concepts:
        for cmd in c.setup_commands:
            pkg = _parse_pkg_from_cmd(cmd)
            if pkg and cmd.startswith("npm install -D "):
                npm_dev.append(pkg)
            elif pkg and cmd.startswith("npm install "):
                npm_deps.append(pkg)
            elif pkg and cmd.startswith(("pip install ", "uv add ")):
                pip_deps.append(pkg)
            else:
                other_cmds.append(cmd)

    lines = [
        "#!/usr/bin/env bash",
        f"# Setup script for {project.name}",
        f"# Generated by Nexus on {datetime.now(UTC).strftime('%Y-%m-%d %H:%M')}",
        f"# Concepts: {len(concepts)}",
        "",
        'set -euo pipefail',
        "",
    ]

    if context_query:
        lines.append(f'echo "Context: "{shlex.quote(context_query)}')
        lines.append("")

    if npm_deps or npm_dev:
        lines.append("# --- Node.js dependencies ---")
        lines.append("if ! command -v npm &> /dev/null; then")
        lines.append('  echo "npm not found, skipping Node.js deps"')
        lines.append("else")
        if npm_deps:
            quoted = " ".join(shlex.quote(p) for p in sorted(npm_deps))
            lines.append(f"  npm install {quoted}")
        if npm_dev:
            quoted = " ".join(shlex.quote(p) for p in sorted(npm_dev))
            lines.append(f"  npm install -D {quoted}")
        lines.append("fi")
        lines.append("")

    if pip_deps:
        quoted = " ".join(shlex.quote(p) for p in sorted(pip_deps))
        lines.append("# --- Python dependencies ---")
        lines.append("if command -v uv &> /dev/null; then")
        lines.append(f"  uv add {quoted}")
        lines.append("elif command -v pip &> /dev/null; then")
        lines.append(f"  pip install {quoted}")
        lines.append("else")
        lines.append('  echo "Neither uv nor pip found, skipping Python deps"')
        lines.append("fi")
        lines.append("")

    for cmd in other_cmds:
        lines.append(f"# REVIEW: {cmd}")

    _append_config_files(concepts, lines)

    pname = shlex.quote(project.name)
    lines.append("")
    lines.append(f'echo "Done -- installed {len(concepts)} tools for "{pname}')
    return "\n".join(lines) + "\n"


def _parse_pkg_from_cmd(cmd: str) -> str | None:
    parts = cmd.split()
    if len(parts) < 2:
        return None
    raw = parts[-1]
    return _safe_pkg_name(raw)


def _filter_concepts(
    conn: sqlite3.Connection, project_id: str,
    context_query: str | None,
) -> list[Concept]:
    concepts = list_concepts(conn, limit=500, project_id=project_id)
    installable = [c for c in concepts if c.setup_commands]
    if not context_query:
        return installable

    from nexus.ai import cosine_similarity, embed
    qvec = embed(context_query)
    if not qvec:
        return installable

    scored = []
    for c in installable:
        if c.embedding:
            sim = cosine_similarity(qvec, c.embedding)
            if sim > 0.4:
                scored.append((c, sim))
    scored.sort(key=lambda x: x[1], reverse=True)
    return [c for c, _ in scored[:15]]


def _append_config_files(concepts: list[Concept], lines: list[str]) -> None:
    has_configs = [c for c in concepts if c.config_files]
    if not has_configs:
        return
    eof_marker = f"NEXUS_EOF_{uuid.uuid4().hex[:8]}"
    lines.append("# --- Config files ---")
    for c in has_configs:
        for cf in c.config_files:
            path = cf.get("path", "")
            content = cf.get("content", "")
            if not path or not content:
                continue
            if not _is_safe_relative_path(path):
                lines.append(f"# SKIPPED unsafe path: {path!r}")
                continue
            if eof_marker in content:
                lines.append(f"# SKIPPED: content contains heredoc marker for {path!r}")
                continue
            lines.append(f"cat > {shlex.quote(path)} << '{eof_marker}'")
            lines.append(content)
            lines.append(eof_marker)
    lines.append("")


def _is_safe_relative_path(path: str) -> bool:
    if not path or path.startswith("/") or path.startswith("~"):
        return False
    return ".." not in path.split("/")


def list_installable(
    conn: sqlite3.Connection, project_id: str,
) -> list[dict]:
    concepts = list_concepts(conn, limit=500, project_id=project_id)
    return [
        {"id": c.id, "name": c.name, "category": c.category,
         "setup_commands": c.setup_commands}
        for c in concepts if c.setup_commands
    ]
