from __future__ import annotations

import sqlite3
from datetime import datetime

from nexus.db import get_project, list_concepts
from nexus.models import Concept


def generate_setup_script(
    conn: sqlite3.Connection, project_id: str,
    *, context_query: str | None = None,
) -> str:
    project = get_project(conn, project_id)
    if not project:
        return "# Error: project not found\n"

    concepts = _filter_concepts(conn, project_id, context_query)
    if not concepts:
        return f"# No installable concepts found for {project.name}\n"

    npm_deps: list[str] = []
    npm_dev: list[str] = []
    pip_deps: list[str] = []
    other_cmds: list[str] = []

    for c in concepts:
        for cmd in c.setup_commands:
            if cmd.startswith("npm install -D "):
                npm_dev.append(cmd.split()[-1])
            elif cmd.startswith("npm install "):
                npm_deps.append(cmd.split()[-1])
            elif cmd.startswith(("pip install ", "uv add ")):
                pip_deps.append(cmd.split()[-1])
            else:
                other_cmds.append(cmd)

    lines = [
        "#!/usr/bin/env bash",
        f"# Setup script for {project.name}",
        f"# Generated by Nexus on {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"# Concepts: {len(concepts)}",
        "",
        'set -euo pipefail',
        "",
    ]

    if context_query:
        lines.append(f'echo "Context: {context_query}"')
        lines.append("")

    if npm_deps or npm_dev:
        lines.append("# --- Node.js dependencies ---")
        lines.append("if ! command -v npm &> /dev/null; then")
        lines.append('  echo "npm not found, skipping Node.js deps"')
        lines.append("else")
        if npm_deps:
            lines.append(f"  npm install {' '.join(sorted(npm_deps))}")
        if npm_dev:
            lines.append(f"  npm install -D {' '.join(sorted(npm_dev))}")
        lines.append("fi")
        lines.append("")

    if pip_deps:
        lines.append("# --- Python dependencies ---")
        lines.append("if command -v uv &> /dev/null; then")
        lines.append(f"  uv add {' '.join(sorted(pip_deps))}")
        lines.append("elif command -v pip &> /dev/null; then")
        lines.append(f"  pip install {' '.join(sorted(pip_deps))}")
        lines.append("else")
        lines.append('  echo "Neither uv nor pip found, skipping Python deps"')
        lines.append("fi")
        lines.append("")

    for cmd in other_cmds:
        lines.append(cmd)

    _append_config_files(concepts, lines)

    lines.append("")
    lines.append(f'echo "Done — installed {len(concepts)} tools for {project.name}"')
    return "\n".join(lines) + "\n"


def _filter_concepts(
    conn: sqlite3.Connection, project_id: str,
    context_query: str | None,
) -> list[Concept]:
    concepts = list_concepts(conn, limit=500, project_id=project_id)
    installable = [c for c in concepts if c.setup_commands]
    if not context_query:
        return installable

    from nexus.ai import cosine_similarity, embed
    qvec = embed(context_query)
    if not qvec:
        return installable

    scored = []
    for c in installable:
        if c.embedding:
            sim = cosine_similarity(qvec, c.embedding)
            if sim > 0.4:
                scored.append((c, sim))
    scored.sort(key=lambda x: x[1], reverse=True)
    return [c for c, _ in scored[:15]]


def _append_config_files(concepts: list[Concept], lines: list[str]) -> None:
    has_configs = [c for c in concepts if c.config_files]
    if not has_configs:
        return
    lines.append("# --- Config files ---")
    for c in has_configs:
        for cf in c.config_files:
            path = cf.get("path", "")
            content = cf.get("content", "")
            if path and content:
                escaped = content.replace("'", "'\\''")
                lines.append(f"cat > '{path}' << 'NEXUS_EOF'")
                lines.append(escaped)
                lines.append("NEXUS_EOF")
    lines.append("")


def list_installable(
    conn: sqlite3.Connection, project_id: str,
) -> list[dict]:
    concepts = list_concepts(conn, limit=500, project_id=project_id)
    return [
        {"id": c.id, "name": c.name, "category": c.category,
         "setup_commands": c.setup_commands}
        for c in concepts if c.setup_commands
    ]
